# Generated by Django 3.2.18 on 2023-03-18 21:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_customuser_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScraperStaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateJoined', models.DateTimeField(auto_now_add=True)),
                ('staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff', to=settings.AUTH_USER_MODEL, verbose_name='Staff')),
                ('staffOf', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin', to=settings.AUTH_USER_MODEL, verbose_name='Admin')),
            ],
        ),
        migrations.CreateModel(
            name='ScraperAdminProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('businessName', models.CharField(max_length=100, verbose_name='Business Name')),
                ('ownerName', models.CharField(max_length=100, verbose_name='Owner Name')),
                ('phoneNumber', models.CharField(max_length=100, verbose_name='PhoneNumber')),
                ('pincode', models.CharField(max_length=100, verbose_name='Pincode')),
                ('village', models.CharField(max_length=100, verbose_name='Village Name')),
                ('subDistrict', models.CharField(max_length=100, verbose_name='SubDistrict')),
                ('district', models.CharField(max_length=100, verbose_name='District')),
                ('state', models.CharField(max_length=100, verbose_name='State Name')),
                ('staffs', models.ManyToManyField(blank=True, related_name='scraperstaffs', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scraperadmin', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
