# Generated by Django 3.2.18 on 2023-03-20 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_scraperadminprofile_scraperstaffprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='scraperadminprofile',
            name='latitude',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='scraperadminprofile',
            name='longitude',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
    ]
