# Generated by Django 3.2.18 on 2023-03-25 09:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20230320_0715'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryName', models.CharField(max_length=100, verbose_name='Category Name')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemName', models.CharField(max_length=100, verbose_name='Item Name')),
                ('rate', models.IntegerField(null=True, verbose_name='Item Rate')),
                ('unit', models.CharField(choices=[('Kg', 'Kilogram'), ('PCs', 'Pieces')], max_length=5, null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.category', verbose_name='Item Category')),
            ],
        ),
        migrations.CreateModel(
            name='SellRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requestedDate', models.DateTimeField(auto_now_add=True)),
                ('requestStatus', models.CharField(choices=[('Requested', 'Requested'), ('Accepted', 'Accepted'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Requested', max_length=10, null=True)),
                ('items', models.ManyToManyField(to='base.Item')),
                ('requestedUser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Requested User')),
            ],
        ),
    ]
