# Generated by Django 3.2.18 on 2023-03-25 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_sellrequest_requesteddate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellrequest',
            name='requestedDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
