# Generated by Django 3.2.18 on 2023-03-25 16:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_sellrequest_requesteddate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requestStatus', models.CharField(choices=[('Accepted', 'Accepted'), ('Completed', 'Completed'), ('Request cancelled', 'Request cancelled'), ('Order cancelled', 'Order cancelled')], default='Accepted', max_length=20, null=True)),
                ('pickupDate', models.DateField()),
                ('totalPrice', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('completedDate', models.DateTimeField(blank=True, null=True)),
                ('acceptedDate', models.DateField(auto_now_add=True)),
                ('acceptedUser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_user', to=settings.AUTH_USER_MODEL, verbose_name='Accepted User')),
                ('completedUser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_user', to=settings.AUTH_USER_MODEL, verbose_name='Completed User')),
                ('sellRequest', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.sellrequest')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewText', models.CharField(max_length=500)),
                ('reviewedDate', models.DateField(auto_now_add=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='base.order')),
                ('reviewedUser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Reviewed User')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addressName', models.CharField(blank=True, max_length=200, null=True)),
                ('city', models.CharField(blank=True, max_length=200, null=True)),
                ('village', models.CharField(blank=True, max_length=200, null=True)),
                ('postalCode', models.CharField(blank=True, max_length=200, null=True)),
                ('landmark', models.CharField(blank=True, max_length=300, null=True)),
                ('houseOrFlatNo', models.CharField(blank=True, max_length=200, null=True)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('phoneNumber', models.CharField(blank=True, max_length=12, null=True)),
                ('sellRequest', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.sellrequest')),
            ],
        ),
    ]
